global:
    scrape_interval: 5s
    scrape_timeout: 5s

scrape_configs:
  - job_name: "nut"
    static_configs:
      # NUT server
      - targets: ["manus:3493"]
    metrics_path: /nut
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # NUT exporter
        replacement: nut-exporter:9995
